"use client";
import { toast } from "sonner";
import type { LanguageCodeType, LanguageLevelsType, WordType } from "@/types";
import { seedWordsByTopic } from "@/lib/actions/admin/seedWordsByTopic";
import TopicGenerationForm from "../forms/GenerationByTopicForm";

interface GenerationByTopicSectionProps {
  isGenerating: boolean;
  setIsGenerating: (value: boolean) => void;
}

const GenerationByTopicSection = ({
  isGenerating,
  setIsGenerating,
}: GenerationByTopicSectionProps) => {
  const handleGenerateWords = async ({
    level,
    total,
    batchSize,
    delay,
    wordType,
    language,
  }: {
    level: LanguageLevelsType;
    total: number;
    batchSize: number;
    delay: number;
    wordType: WordType;
    language: LanguageCodeType;
  }) => {
    try {
      setIsGenerating(true);

      const {
        success,
        data: totalGenerated,
        error,
      } = await seedWordsByTopic({
        total,
        batchSize,
        wordType,
        delayMs: delay,
        level,
        language,
      });

      if (success) {
        toast.success("Words generated by topic", {
          description: `Successfully generated ${totalGenerated} words at level ${level.toUpperCase()} for ${language.toUpperCase()}.`,
        });
      } else {
        toast.error("Failed to generate words", {
          description:
            error instanceof Error
              ? error.message
              : "An unknown error occurred",
        });
      }
    } catch (error) {
      toast.error("Unexpected error during generation");
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="w-full">
      <TopicGenerationForm
        isGenerating={isGenerating}
        onGenerate={handleGenerateWords}
      />
    </div>
  );
};

export default GenerationByTopicSection;
