import { LanguageLevels } from "@/types";

export const WORDS_CATEGORIES = [
  "Greetings",
  "Family",
  "Friends",
  "Daily Life",
  "Food",
  "Hobbies",
  "Travel",
  "Work",
  "Education",
  "Home",
  "Shopping",
  "Health",
  "Weather",
  "Time",
  "Numbers",
  "Colors",
  "Animals",
  "Music",
  "Books",
  "Sports",
  "Technology",
  "Internet",
  "News",
  "Money",
  "Transport",
  "Language",
  "Countries",
  "Festivals",
  "Childhood",
  "Dreams",
  "Opinions",
  "Problems",
  "Plans",
  "Memories",
  "Nature",
  "Art",
  "Fashion",
  "Emotions",
  "Directions",
  "Appointments",
  "Restaurants",
  "Doctor",
  "Past",
  "Future",
  "Agreement",
  "Suggestions",
  "Advice",
  "Thanks",
  "Apologies",
  "Appearance",
  "Beliefs",
  "Business",
  "Celebrations",
  "Changes",
  "City Life",
  "Clothes",
  "Communication",
  "Community",
  "Comparisons",
  "Computers",
  "Cooking",
  "Countryside",
  "Culture",
  "Decisions",
  "Descriptions",
  "Entertainment",
  "Environment",
  "Events",
  "Excuses",
  "Experiences",
  "Feelings",
  "Finance",
  "Games",
  "Gardening",
  "History",
  "Holidays",
  "Humor",
  "Ideas",
  "Imagination",
  "Inventions",
  "Law",
  "Leisure",
  "Love",
  "Machines",
  "Media",
  "Meetings",
  "Mistakes",
  "Motivation",
  "Names",
  "Needs",
  "Organizations",
  "Parties",
  "Personalities",
  "Pets",
  "Places",
  "Possessions",
  "Predictions",
  "Relationships",
  "Safety",
  "Science",
  "Secrets",
  "Senses",
  "Silence",
  "Sleep",
  "Smells",
  "Solutions",
  "Sounds",
  "Space (Outer)",
  "Stages of Life",
  "Stories",
  "Stress",
  "Success",
  "Surprises",
  "Tastes",
  "Technology Trends",
  "Thoughts",
  "Traditions",
  "Traffic",
  "Tragedy",
  "Trends",
  "Understanding",
  "Vacations",
  "Values",
  "Violence",
  "Virtues",
  "Visions",
  "Volunteering",
  "Weaknesses",
  "Wealth",
  "Wishes",
  "Wonder",
  "Words",
  "World Issues",
  "Writing",
  "Youth",
  "Zoos",
  "Ambitions",
  "Annoyances",
  "Choices",
  "Comfort",
  "Creativity",
  "Curiosity",
  "Danger",
  "Debates",
  "Discoveries",
  "Dreams (Nighttime)",
  "Effort",
];

export const WORDS_LANGUAGE_LEVELS: LanguageLevels[] = [
  "A0",
  "A1",
  "A2",
  "B1",
  "B2",
  "C1",
  "C2",
];

export const WORD_TYPE_WEIGHTS = {
  rzeczownik: 30, // noun
  czasownik: 25, // verb
  przymiotnik: 15, // adjective
  przysłówek: 10, // adverb
  przyimek: 5, // preposition
  partykuła: 5, // particle
  liczebnik: 5, // numeral
  zaimek: 5, // pronoun
};

export const SCENARIOS = [];
