import { plVocabulary, ruVocabulary } from "@/db/schema";
import { LanguageWordType } from "@/db/types";
import { LanguageCodeType, LanguageLevelsType, WordType } from "@/types";

export const WORDS_CATEGORIES = [
  "Greetings",
  "Family",
  "Friends",
  "Daily Life",
  "Food",
  "Hobbies",
  "Travel",
  "Work",
  "Education",
  "Home",
  "Shopping",
  "Health",
  "Weather",
  "Time",
  "Numbers",
  "Colors",
  "Animals",
  "Music",
  "Books",
  "Sports",
  "Technology",
  "Internet",
  "News",
  "Money",
  "Transport",
  "Language",
  "Countries",
  "Festivals",
  "Childhood",
  "Dreams",
  "Opinions",
  "Problems",
  "Plans",
  "Memories",
  "Nature",
  "Art",
  "Fashion",
  "Emotions",
  "Directions",
  "Appointments",
  "Restaurants",
  "Doctor",
  "Past",
  "Future",
  "Agreement",
  "Suggestions",
  "Advice",
  "Thanks",
  "Apologies",
  "Appearance",
  "Beliefs",
  "Business",
  "Celebrations",
  "Changes",
  "City Life",
  "Clothes",
  "Communication",
  "Community",
  "Comparisons",
  "Computers",
  "Cooking",
  "Countryside",
  "Culture",
  "Decisions",
  "Descriptions",
  "Entertainment",
  "Environment",
  "Events",
  "Excuses",
  "Experiences",
  "Feelings",
  "Finance",
  "Games",
  "Gardening",
  "History",
  "Holidays",
  "Humor",
  "Ideas",
  "Imagination",
  "Inventions",
  "Law",
  "Leisure",
  "Love",
  "Machines",
  "Media",
  "Meetings",
  "Mistakes",
  "Motivation",
  "Names",
  "Needs",
  "Organizations",
  "Parties",
  "Personalities",
  "Pets",
  "Places",
  "Possessions",
  "Predictions",
  "Relationships",
  "Safety",
  "Science",
  "Secrets",
  "Senses",
  "Silence",
  "Sleep",
  "Smells",
  "Solutions",
  "Sounds",
  "Space (Outer)",
  "Stages of Life",
  "Stories",
  "Stress",
  "Success",
  "Surprises",
  "Tastes",
  "Technology Trends",
  "Thoughts",
  "Traditions",
  "Traffic",
  "Tragedy",
  "Trends",
  "Understanding",
  "Vacations",
  "Values",
  "Violence",
  "Virtues",
  "Visions",
  "Volunteering",
  "Weaknesses",
  "Wealth",
  "Wishes",
  "Wonder",
  "Words",
  "World Issues",
  "Writing",
  "Youth",
  "Zoos",
  "Ambitions",
  "Annoyances",
  "Choices",
  "Comfort",
  "Creativity",
  "Curiosity",
  "Danger",
  "Debates",
  "Discoveries",
  "Dreams (Nighttime)",
  "Effort",
];

export const WORDS_LANGUAGE_LEVELS: LanguageLevelsType[] = [
  "A0",
  "A1",
  "A2",
  "B1",
  "B2",
  "C1",
  "C2",
];

export const WORD_TYPES: Record<
  LanguageCodeType,
  Record<WordType, LanguageWordType[LanguageCodeType]>
> = {
  pl: {
    noun: "rzeczownik",
    verb: "czasownik",
    adjective: "przymiotnik",
    adverb: "przysłówek",
    numeral: "liczebnik",
    pronoun: "zaimek",
    preposition: "przyimek",
    conjunction: "spójnik",
    particle: "partykuła",
  },
  ru: {
    noun: "существительное",
    verb: "глагол",
    adjective: "прилагательное",
    adverb: "наречие",
    numeral: "числительное",
    pronoun: "местоимение",
    preposition: "предлог",
    conjunction: "союз",
    particle: "частица",
  },
};

export const WORD_TYPES_PROMPTS: Record<
  LanguageCodeType,
  Record<WordType, string>
> = {
  pl: {
    noun: "- Słowa powinny być 'rzeczownikami' w liczbie pojedynczej i w 'mianowniku'.",
    verb: "- Słowa powinny być 'czasownikami' w formie podstawowej (bezokolicznik).",
    adjective:
      "- Słowa powinny być 'przymiotnikami' w rodzaju męskim, liczbie pojedynczej i w 'mianowniku'.",
    adverb:
      "- Słowa powinny być 'przysłówkami' w podstawowej, nieodmiennej formie.",
    numeral:
      "- Słowa powinny być 'liczebnikami', najlepiej głównymi, w formie podstawowej.",
    pronoun:
      "- Słowa powinny być 'zaimkami' — osobowymi, dzierżawczymi lub wskazującymi w mianowniku.",
    preposition:
      "- Słowa powinny być 'przyimkami' powszechnie używanymi we współczesnym języku polskim.",
    conjunction:
      "- Słowa powinny być 'spójnikami', które łączą zdania lub ich części.",
    particle: "- Słowa powinny być 'partykulami'.",
  },
  ru: {
    noun: "- Слова должны быть 'существительными' в единственном числе и в 'именительном падеже'.",
    verb: "- Слова должны быть 'глаголами' в начальной форме (инфинитив).",
    adjective:
      "- Слова должны быть 'прилагательными' в мужском роде, единственном числе и в 'именительном падеже'.",
    adverb: "- Слова должны быть 'наречиями' в базовой, несклоняемой форме.",
    numeral:
      "- Слова должны быть 'числительными', предпочтительно количественными в их начальной форме.",
    pronoun:
      "- Слова должны быть 'местоимениями' — личными, притяжательными или указательными в именительном падеже.",
    preposition:
      "- Слова должны быть 'предлогами', часто используемыми в современном русском языке.",
    conjunction:
      "- Слова должны быть 'союзами', которые соединяют предложения или части предложений.",
    particle: "- Слова должны быть 'частицами'.",
  },
} as const;

export const LEVEL_OPTIONS = [
  { value: "random", label: "Random" },
  { value: "A0", label: "A0" },
  { value: "A1", label: "A1" },
  { value: "A2", label: "A2" },
  { value: "B1", label: "B1" },
  { value: "B2", label: "B2" },
  { value: "C1", label: "C1" },
  { value: "C2", label: "C2" },
];

export const WORDS_TYPES_OPTIONS = [
  { value: "none", label: "Any type" },
  { value: "noun", label: "Noun" },
  { value: "verb", label: "Verb" },
  { value: "adjective", label: "Adjective" },
  { value: "adverb", label: "Adverb" },
  { value: "numeral", label: "Numeral" },
];

export const ALPHABETS = {
  pl: [
    "a",
    "b",
    "c",
    "ć",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "ł",
    "m",
    "n",
    "ń",
    "o",
    "ó",
    "p",
    "r",
    "s",
    "ś",
    "t",
    "u",
    "w",
    "y",
    "z",
    "ź",
    "ż",
  ],
  ru: [
    "а",
    "б",
    "в",
    "г",
    "д",
    "е",
    "ё",
    "ж",
    "з",
    "и",
    "й",
    "к",
    "л",
    "м",
    "н",
    "о",
    "п",
    "р",
    "с",
    "т",
    "у",
    "ф",
    "х",
    "ц",
    "ч",
    "ш",
    "щ",
    "ъ",
    "ы",
    "ь",
    "э",
    "ю",
    "я",
  ],
};

export const vocabTables = {
  pl: plVocabulary,
  ru: ruVocabulary,
} as const;

export const vocabTablesNames = {
  pl: "pl_vocabulary",
  ru: "ru_vocabulary",
};
