import { plVocabulary, ruVocabulary } from "@/db/schema";
import { LanguageLevelsType } from "@/types";

export const WORDS_CATEGORIES = [
  "Greetings",
  "Family",
  "Friends",
  "Daily Life",
  "Food",
  "Hobbies",
  "Travel",
  "Work",
  "Education",
  "Home",
  "Shopping",
  "Health",
  "Weather",
  "Time",
  "Numbers",
  "Colors",
  "Animals",
  "Music",
  "Books",
  "Sports",
  "Technology",
  "Internet",
  "News",
  "Money",
  "Transport",
  "Language",
  "Countries",
  "Festivals",
  "Childhood",
  "Dreams",
  "Opinions",
  "Problems",
  "Plans",
  "Memories",
  "Nature",
  "Art",
  "Fashion",
  "Emotions",
  "Directions",
  "Appointments",
  "Restaurants",
  "Doctor",
  "Past",
  "Future",
  "Agreement",
  "Suggestions",
  "Advice",
  "Thanks",
  "Apologies",
  "Appearance",
  "Beliefs",
  "Business",
  "Celebrations",
  "Changes",
  "City Life",
  "Clothes",
  "Communication",
  "Community",
  "Comparisons",
  "Computers",
  "Cooking",
  "Countryside",
  "Culture",
  "Decisions",
  "Descriptions",
  "Entertainment",
  "Environment",
  "Events",
  "Excuses",
  "Experiences",
  "Feelings",
  "Finance",
  "Games",
  "Gardening",
  "History",
  "Holidays",
  "Humor",
  "Ideas",
  "Imagination",
  "Inventions",
  "Law",
  "Leisure",
  "Love",
  "Machines",
  "Media",
  "Meetings",
  "Mistakes",
  "Motivation",
  "Names",
  "Needs",
  "Organizations",
  "Parties",
  "Personalities",
  "Pets",
  "Places",
  "Possessions",
  "Predictions",
  "Relationships",
  "Safety",
  "Science",
  "Secrets",
  "Senses",
  "Silence",
  "Sleep",
  "Smells",
  "Solutions",
  "Sounds",
  "Space (Outer)",
  "Stages of Life",
  "Stories",
  "Stress",
  "Success",
  "Surprises",
  "Tastes",
  "Technology Trends",
  "Thoughts",
  "Traditions",
  "Traffic",
  "Tragedy",
  "Trends",
  "Understanding",
  "Vacations",
  "Values",
  "Violence",
  "Virtues",
  "Visions",
  "Volunteering",
  "Weaknesses",
  "Wealth",
  "Wishes",
  "Wonder",
  "Words",
  "World Issues",
  "Writing",
  "Youth",
  "Zoos",
  "Ambitions",
  "Annoyances",
  "Choices",
  "Comfort",
  "Creativity",
  "Curiosity",
  "Danger",
  "Debates",
  "Discoveries",
  "Dreams (Nighttime)",
  "Effort",
];

export const WORDS_LANGUAGE_LEVELS: LanguageLevelsType[] = [
  "A0",
  "A1",
  "A2",
  "B1",
  "B2",
  "C1",
  "C2",
];

export const WORD_TYPES_PL_PROMPTS = {
  noun: "- Words should be 'rzeczowniki' (nouns) in their singular and 'mianownik' (nominative) forms.",
  verb: "- Words should be 'czasowniki' (verbs) in the 'bezokolicznik' (infinitive) form.",
  adjective:
    "- Words should be 'przymiotniki' (adjectives) in their singular masculine 'mianownik' (nominative) form.",
  adverb:
    "- Words should be 'przysłówki' (adverbs) in their base, non-comparative form.",
  numeral:
    "- Words should be 'liczebniki' (numerals), specifically cardinal numbers in their basic form.",
  pronouns:
    "- Words should be 'zaimki' (pronouns), such as personal, possessive, or demonstrative pronouns in nominative case.",
  prepositions:
    "- Words should be 'przyimki' (prepositions) commonly used in modern Polish.",
  conjunctions:
    "- Words should be 'spójniki' (conjunctions) used to connect clauses or sentences.",
} as const;

export const LEVEL_OPTIONS = [
  { value: "random", label: "Random" },
  { value: "A0", label: "A0" },
  { value: "A1", label: "A1" },
  { value: "A2", label: "A2" },
  { value: "B1", label: "B1" },
  { value: "B2", label: "B2" },
  { value: "C1", label: "C1" },
  { value: "C2", label: "C2" },
];

export const WORDS_TYPES_OPTIONS = [
  { value: "none", label: "Any type" },
  { value: "noun", label: "Noun" },
  { value: "verb", label: "Verb" },
  { value: "adjective", label: "Adjective" },
  { value: "adverb", label: "Adverb" },
  { value: "numeral", label: "Numeral" },
];

export const ALPHABETS = {
  pl: [
    "a",
    "b",
    "c",
    "ć",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "ł",
    "m",
    "n",
    "ń",
    "o",
    "ó",
    "p",
    "r",
    "s",
    "ś",
    "t",
    "u",
    "w",
    "y",
    "z",
    "ź",
    "ż",
  ],
  ru: [
    "а",
    "б",
    "в",
    "г",
    "д",
    "е",
    "ё",
    "ж",
    "з",
    "и",
    "й",
    "к",
    "л",
    "м",
    "н",
    "о",
    "п",
    "р",
    "с",
    "т",
    "у",
    "ф",
    "х",
    "ц",
    "ч",
    "ш",
    "щ",
    "ъ",
    "ы",
    "ь",
    "э",
    "ю",
    "я",
  ],
};

export const vocabTables = {
  pl: plVocabulary,
  ru: ruVocabulary,
} as const;

export const vocabTablesNames = {
  pl: "pl_vocabulary",
  ru: "ru_vocabulary",
};
